parameters:
    mailer.gmail_user: "yassine@gmail.com"
    mailer.gmail_password: "123456"

services:
    _instanceof:
      App\HasLoggerInterface:
       # add tag #with_logger for all classes imp  i: HasLoggerInterface
        tags: ["with_logger"]

    _defaults:
      autowire: true

    oreder_controller:
      class: App\Controller\OrderController
      public: true
      calls:
        - method: sayHello
          arguments:
            - "Bonjour a Tous"
            - 77
        - method: setSecondaryMailer
          arguments:
            - "@mailer.gmail"
    database:
      class: App\Database\Database

    mailer.gmail:
      class: App\Mailer\GmailMailer
      arguments: [ "%mailer.gmail_user%", "%mailer.gmail_password%"]
      #tags: ["with_logger"] :: look attr: services/_instanceof

    texter.sms:
      class: App\Texter\SmsTexter
      arguments: [ "service.sms.com", "apikey123"]
      #tags: ["with_logger"] :: look attr: services/_instanceof

    texter.fax:
      class: App\Texter\FaxTexter

    mailer.smtp:
      class: App\Mailer\SmtpMailer
      arguments: ['smtp://localhost', 'root', '123']

    logger:
      class: App\Logger

    App\Controller\OrderController:
      alias: oreder_controller
      public: true 
      
    # alias :
    App\Database\Database: '@database'
    App\Mailer\GmailMailer: '@mailer.gmail'
    App\Mailer\SmtpMailer: '@mailer.smtp'
    App\Mailer\MailerInterface: '@mailer.gmail'
    App\Texter\SmsTexter: '@texter.sms'
    App\Texter\FaxTexter: '@texter.fax'
    App\Texter\TexterInterface: '@texter.sms'
    App\Logger: '@logger'
  
